language: cpp

git:
  depth: 1

notifications:
  email: false

matrix:
  matrix: 
  include:
  - os: osx
    osx_image: xcode9.2
    compiler: clang
  - os: linux
    dist: trusty
    group: latest
    sudo: required
    services: docker

before_install:
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    cd ..
    pwd
    docker run -d --name ubuntu --privileged -v $(pwd):/benkuper ubuntu:latest tail -f /dev/null
    docker ps
  else
    gem install xcpretty
    gem install xcpretty-travis-formatter
    pwd
    ls -d */
    cd /Users/travis
    git clone --depth=1 --branch=develop-local https://github.com/benkuper/JUCE.git JUCE
    cd /Users/travis/build/benkuper
    mkdir "JUCE Modules"
    cd "JUCE Modules"
    git clone --depth=1 --branch=master https://github.com/benkuper/juce_organicui.git juce_organicui
    git clone --depth=1 --branch=master https://github.com/benkuper/juce_timeline.git juce_timeline
    cd ..
    pwd
    ls -d */
  fi
install:
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    docker exec -t ubuntu bash -c "export DEBIAN_FRONTEND=noninteractive;
    uname -a;
    apt-get install software-properties-common
    add-apt-repository ppa:webkit-team/ppa -y;
    add-apt-repository -y ppa:ubuntu-toolchain-r/test;
    apt-get update --fix-missing;
    apt-get update -qq;
    echo 'Installing GCC...';
    apt-get install -y g++-7 gcc-7;
    gcc -v;
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90;
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90;
    export CC=/usr/bin/gcc;
    export CXX=/usr/bin/g++;
    echo ${CC};
    echo ${CXX};
    apt-get install -qq git libfreetype6-dev libx11-dev libxinerama-dev libxrandr-dev libxcursor-dev libxcomposite-dev mesa-common-dev libasound2-dev freeglut3-dev libcurl4-gnutls-dev+ libasound2-dev libjack-dev libbluetooth-dev libgtk-3-dev libwebkit2gtk-4.0-dev curl wget zip unzip libfuse2 > /dev/null;
    cd ~;
    pwd;
    git clone --depth=1 --branch=develop-local https://github.com/benkuper/JUCE.git JUCE;
    cd /benkuper;
    mkdir 'JUCE Modules';
    cd 'JUCE Modules';
    git clone --depth=1 --branch=master https://github.com/benkuper/juce_organicui.git juce_organicui
    git clone --depth=1 --branch=master https://github.com/benkuper/juce_sharedtexture.git juce_sharedtexture
    git clone --depth=1 --branch=master https://github.com/benkuper/juce_timeline.git juce_timeline"
  fi
script:
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    docker exec -t ubuntu bash -c "gcc -v;
    cd /benkuper/BenTo/Builds/LinuxMakefile;
    make -j 8 CONFIG=Release"
  else
    xcodebuild -project BenTo/Builds/MacOSX_CI/BenTo.xcodeproj -configuration Release -jobs 8 | xcpretty -f `xcpretty-travis-formatter`
  fi
after_success:
- |-
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    docker exec -t ubuntu bash -c "cd /benkuper/BenTo/Builds/LinuxMakefile;
    pwd
    echo 'Downloading AppImageTool...';
    wget "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage";
    chmod a+x appimagetool-x86_64.AppImage;
    echo 'Packaging AppImage...';
    mkdir BenTo.AppDir/usr/;
    mkdir BenTo.AppDir/usr/bin/;
    cp build/BenTo BenTo.AppDir/usr/bin/;
    ./appimagetool-x86_64.AppImage BenTo.AppDir BenTo-linux-x64-$SUFFIX.AppImage;
    echo 'Uploading $SUFFIX ...';
    curl -X POST -F 'appFile=@BenTo-linux-x64-$SUFFIX.AppImage' -F 'pass=$UPLOAD_PASS' -F 'path=bento/' $UPLOAD_URL;"
  else
    cd /Users/travis/build/benkuper/BenTo/Builds/MacOSX_CI/build/Release
    ls
    zip -r -y BenTo-osx-bleedingedge.zip BenTo.app
    curl --ftp-create-dirs -T BenTo-osx-bleedingedge.zip -u $FTP_USER:$FTP_PASSWORD --insecure ftp://home403871847.1and1-data.host/bento/
  fi
